Repository dezh-tech/immortal, pull requests merged in 2024-09, with the labels that each got.

#9 feat(types): add basic Nostr types
  CONTRIBUTING.md
  go.mod
  go.sum
  types/envelope/envelope.go
  types/envelope/envelope_test.go
  types/event.go
  types/event/event.go
  types/event/event_easyjson.go
  types/event/event_test.go
  types/filter.go
  types/filter/filter.go
  types/filter/filter_easyjson.go
  types/filter/filter_test.go
  types/kind.go
  types/message.go
  types/tag.go
  types/utils.go
Labels: NIPs

#23 feat(relay): add websocket.
  .golangci.yml
  cmd/main.go
  go.mod
  go.sum
  relay/relay.go
  types/envelope/envelope.go
  types/errors.go
  types/event/event.go
  types/event/event_easyjson.go
  types/filter/filter.go
  types/message/message.go
  types/message/message_test.go
  types/utils.go
Labels: NIPs, websocket

#35 feat(relay): gracefully shutdown
  cmd/commands/help.go
  cmd/commands/run.go
  cmd/main.go
  relay/relay.go
  server/server.go
Labels: enhancement

#37 docs: add more documents
  CONTRIBUTING.md
  documents/NIPs.md
  documents/development.md
  documents/update-dependencies.md
  documents/user/backup.md
  documents/user/metrics-logs.md
  documents/user/running.md
  documents/user/update.md
  documents/version-release.md
  version.go
Labels: documentation

#38 fix(server): client handling
  server/client.go
  server/server.go
Labels: bug, enhancement, security, performance

#42 fix(database,server): closing database on shutdown, handling bloom errors.
  database/database.go
  relay/relay.go
  server/server.go
  types/filter/filter.go
Labels: bug, database:pg, server

#43 feat(database:pg, server): store incoming events to database.
  .gitignore
  cmd/commands/run.go
  config/config.go
  config/config_test.go
  database/migrations/000001_init.up.sql
  database/models/follow_list.go
  database/models/reactions.go
  database/models/text_notes.go
  database/models/users_metadata.go
  handlers/event_handler.go
  handlers/kind_handler.go
  relay/relay.go
  server/server.go
  sqlboiler.yml
  types/kind.go
  types/message/message.go
Labels: database:pg

#47 fix(types): fix wrong implementation of match method and kind helpers.
  types/event/event.go
  types/filter/filter.go
  types/filter/filter_easyjson.go
  types/filter/filter_test.go
  types/kind.go
  types/message/message_test.go
  types/tag.go
Labels: bug, NIPs

#48 fix(config): loading pg dsn from example file in dev.
  config/.develop_env
  config/config.go
  config/config.yml
  go.mod
  go.sum
  sqlboiler.yml
Labels: bug, database:pg, config

#52 feat(database): migrate to mongo, finish REQ and EVENT.
  config/.develop.env
  config/config.go
  config/config.yml
  database/config.go
  database/database.go
  database/migrations/000001_init.down.sql
  database/migrations/000001_init.up.sql
  database/models/boil_queries.go
  database/models/boil_table_names.go
  database/models/boil_types.go
  database/models/boil_view_names.go
  database/models/follow_list.go
  database/models/psql_upsert.go
  database/models/reactions.go
  database/models/schema_migrations.go
  database/models/text_notes.go
  database/models/users_metadata.go
  deployment/dev/docker-compose.yml
  docker-compose.yml
  documents/NIPs.md
  documents/erd/README.md
  documents/erd/exp/data.zip
  documents/erd/exp/project.xml
  documents/erd/immortal-erd.vpp
  documents/erd/immortal-erd.vpp.bak_000f
  documents/erd/immortal-erd.vpp.bak_001d
  documents/erd/immortal-erd.vpp.bak_002d
  go.mod
  go.sum
  handler/event.go
  handler/handler.go
  handler/req.go
  handlers/event_handler.go
  handlers/kind_handler.go
  server/server.go
  sqlboiler.yml
  types/event/event.go
  types/message/message.go
Labels: enhancement, NIPs, database:mongo
